# Executes commands at the start of an interactive session.
#
# Authors:
#	  Fullchee Zhang <fullchee@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.dotfiles/file-scripts.sh
source $HOME/.dotfiles/git-scripts.sh
source $HOME/.dotfiles/programming-scripts.sh

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# RPROMPT='[%D{%L:%M:%S}] '$RPROMPTE

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# fpath=(~/path/to/wd $fpath)
# export HTTPS=true
# export SSL_CRT_FILE=~/.localhost-ssl/localhost.crt
# export SSL_KEY_FILE=~/.localhost-ssl/localhost.key
export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"

# fixes a problem on M1 macs
# https://apple.stackexchange.com/questions/148901/why-does-my-brew-installation
eval $(/opt/homebrew/bin/brew shellenv)
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
